$(function() {
	$("#product-features-tab").click(function(){
		$(this).addClass("current");
		$("#product-specification-tab").removeClass("current");
		$("#product-packaging-tab").removeClass("current");
		$("#product-accessories-tab").removeClass("current");
		$("#product-features").show();
		$("#product-specification").hide();
		$("#product-packaging").hide();
		$("#product-accessories").hide();
	});
	$("#product-specification-tab").click(function(){
		$(this).addClass("current");
		$("#product-features-tab").removeClass("current");
		$("#product-packaging-tab").removeClass("current");
		$("#product-accessories-tab").removeClass("current");
		$("#product-features").hide();
		$("#product-specification").show();
		$("#product-packaging").hide();
		$("#product-accessories").hide();
	});
	$("#product-packaging-tab").click(function(){
		$(this).addClass("current");
		$("#product-features-tab").removeClass("current");
		$("#product-specification-tab").removeClass("current");
		$("#product-accessories-tab").removeClass("current");
		$("#product-features").hide();
		$("#product-specification").hide();
		$("#product-packaging").show();
		$("#product-accessories").hide();
	});
	$("#product-accessories-tab").click(function(){
		$(this).addClass("current");
		$("#product-features-tab").removeClass("current");
		$("#product-specification-tab").removeClass("current");
		$("#product-packaging-tab").removeClass("current");
		$("#product-features").hide();
		$("#product-specification").hide();
		$("#product-packaging").hide();
		$("#product-accessories").show();
	});
});